spring:
  application:
    name: platformstore
  cloud:
    config:
      import-check:
        enabled: false
      import: configserver:${CONFIG_SERVER_URL:http://configserver:8888}
 

  h2:
    console:
      enabled: true # Включение консоли H2
      settings:
        web-allow-others: true # Разрешение удалённого доступа к консоли
  datasource:
    url: jdbc:h2:file:C:/Users/ostan/test;DB_CLOSE_ON_EXIT=TRUE # URL для подключения к базе данных
    driver-class-name: org.h2.Driver # Драйвер базы данных
    username: sa # Имя пользователя
    password: # Пароль (по умолчанию пустой)
  jpa:
    hibernate:
      ddl-auto: update # Автоматическое создание и обновление схемы базы данных
    show-sql: true # Показ SQL-запросов в логах
  topic:
    send-order: send-order-event
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

server:
  port: 8080

custom:
  property: value

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
