server:
  port: 8072
eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true         
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/ 
  instance:
    lease-renewal-interval-in-seconds: 30  
    lease-expiration-duration-in-seconds: 90  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
management:
  endpoint:
    gateway:
      enabled: true  
  endpoints:
    web:
      exposure:
        include: gateway
